### ISSUE TITLE
src/main/webapp is missing

### ISSUE THREAD

**Issue by m0** [nexus-Six/quarkus-gui-react-patternfly#1]
When trying to build the project as described in the README, npm fails because the `src/main/webapp` folder is missing.

The interesting blog post (thanks for that!) at https://quarkus.io/blog/gui-react-patternfly/ states:
> The sourcecode for the final application can be found [here](https://github.com/nexus-Six/quarkus-gui-react-patternfly).
So I was hoping to find a working project that I can play with. Did I miss something?

**Comment by nexus-Six** [comment]
Thanks for pointing this out. I have just pushed some changes to the repo as well as the README. Please check if it works for you now.
